- hosts: vpc
  vars: #local connection defaults to using the system python
    ansible_python_interpreter: /Users/lauchiulam/Projects/DevOpsTechnicalChallenge/venv/bin/python3
  environment:
    AWS_ACCESS_KEY_ID: "{{ aws_access_key }}"
    AWS_SECRET_ACCESS_KEY: "{{ aws_secret_key }}"
    AWS_REGION: "{{ aws_region }}"
  tasks:

      - name: Delete a EC2 key
        ec2_key:
            name: ansibled-key
            region: ap-east-1
            #  absent means delete keypair
            state: absent